version: "2.30.3"
services:
  website: 
    image: nginx
    ports:
      - "8082:80"
    restart: always
  website2:
    image: nginx
    ports:
      - "8083:80"
    restart: always
    networks:
      ourNetwork:
        ipv4_address: 192.168.92.21
networks:
  ourNetwork:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
