version: '3.5'

services:
  nginx:
    build: ./requirements/nginx
    image: nginx:1337
    container_name: nginx
    depends_on:
    - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress:1337
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb:1337
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql/
    networks:
      - inception
    restart: always

  redis:
    build: ./requirements/bonus/redis/
    image: redis
    container_name: redis
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  adminer:
    build: ./requirements/bonus/adminer/
    image: adminer
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "600:80"
    networks:
      - inception
    restart: always

  cadvisor:
    build: ./requirements/bonus/cadvisor/
    image: cadvisor
    container_name: cadvisor
    networks:
      - inception
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  ftp:
    build: ./requirements/bonus/ftp/
    image: ftp
    container_name: ftp
    depends_on:
      - wordpress
    volumes:
      - wordpress:/home/abdu/ftp/files
    ports:
      - "21:21"
      - "20:20"
      - "4000-4005:4000-4005"
    networks:
      - inception
    env_file:
      - .env



networks:
  inception:

volumes:
  db:
    driver_opts:
      type: none
      o: bind
      device: /home/achahrou/data/db/
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /home/achahrou/data/wordpress/
