version: "27.3.1"
services:
  wordpress:
    networks:
      - ohyeah
    image: wordpress
    ports:
      - "8089:80"
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "elpsy"
      WORDPRESS_DB_NAME: wordpress

  mariadb:
    networks:
      - ohyeah
    image: "mariadb:latest"
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_ROOT_PASSWORD: "elpsy"
    volumes:
    - ./mariadb:/var/lib/mysql

networks:
  ohyeah:
    ipam:
      driver: default
      config:
        - subnet: "10.56.1.0/24"
